### ISSUE TITLE
How to test ?

### ISSUE THREAD

**Issue by strzhao** [beryu/SiriShortcutsSample#1]
how to trigger play ? thanks

**Comment by beryu** [comment]
I just wrote README.md.
Please try it.
https://github.com/beryu/SiriShortcutsSample#usage

**Comment by strzhao** [comment]
thank you very much. So INPlayMediaIntent indeed only used by shortcut. what a pity.

**Comment by beryu** [comment]
Siri has a lot of limitation around music functions.
But SiriShortcuts and INPlayMediaIntent make part of it to be available., I hope this is beginning of publication of music functions by Apple.

By the way, this issue was solved.
I close this!
